### ISSUE TITLE
suitable covariate for WGBS experiment

### ISSUE THREAD

**Issue by MohamedRefaat92** [nignatiadis/IHW#5]
Dear developer,

I'm analyzing a big dataset obtained from Whole Genome Bisulfite Sequencing experiment. The number of regions tested between two conditions is over **500k.** I plan to use your software to correct for multiple testing while increasing the power. 

The challenge I face is which covariate to use. I've checked the package's vignette where you give examples for covariates for different experiments, but not for WGBS.

Would the **number of CpG loci** in a region or the **width of the region** make a suitable covariate for IHW? or maybe the **number of reads aligned** to the loci in a region?

Thanks in advance.

**Comment by nignatiadis** [comment]
Hi Mohamed,

I apologize for my late reply and thank you for your interest in this software and for your feedback. In case you are still looking for suggestions, can I please ask you to post your question to https://support.bioconductor.org? That way
- others also get a chance to contribute,
- other users also benefit from the discussion, and
- the question and answers are publicly archived and become findable
with search engines.

Best,
Nikos
