### ISSUE TITLE
retain annotation when running `ihw()`

### ISSUE THREAD

**Issue by dlaehnemann** [nignatiadis/IHW#6]
We are using IHW in a differential expression pipeline. To be able to interpret results, we need the gene names corresponding to the weighted p-values in the results -- and I assume this what you would usually want, or am I missing some important point here?

However, from what we can see in the documentation and the code, the `ihwResult-class` provides the original pvalues, weights and weighted pvalues, but not any further annotation that came with it. Optimally, using the formula type of calling `ihw()` we would use:

```
ihw_results <- ihw(pvalue ~ covariate, data = per_gene_data)
```

Where `per_gene_data` is a data frame that contains the columns `pvalue` and `covariate` along with further annotation, e.g. the gene names associated with a pair of `pvalue` and `covariate`, so e.g. something like:

```
ens_gene   pvalue   covariate
ENS1234   0.0123   3.45678
ENS2345   0.0234   4.56789
```

For printing out the results into a table (TSV in our case), we turn `ihw_results` into a data frame with `as.data.frame(ihw_results)`. However, this does not contain the `ens_gene` column any more, even though this is essential for the interpretation of the resulting weighted pvalues. We can of course add that info back in manually (and currently do using the [`dplyr` join methods](https://dplyr.tidyverse.org/reference/join.html) on the `pvalue`, the `covariate` and the `grouping` assigned by IHW), but this feels patchy and hacky. We would prefer if ihw() itself did not drop any columns from `per_gene_data`, but just kept all of its columns along for the ride and associated to the right values, including when creating turning the `IHWresults` into a data frame.

Am I making sense? Please do not hesitate to check back for further explanations on any of this.

**Comment by wolfganghuber** [comment]
Dear David,


thank you for your interest in this software and for your feedback. Can 
I please ask you to post your question to 
https://support.bioconductor.org? That way
- others also get a chance to contribute,
- other users also benefit from the discussion, and
- the question and answers are publicly archived and become findable 
with search engines.

Wolfgang


15.4.20 17:48, David Laehnemann scripsit:

**Comment by dlaehnemann** [comment]
Dear Wolfgang,

sure thing, the question is now also online over there:
https://support.bioconductor.org/p/129972/

And I'll close this issue in favour of a discussion on the bioconductor support forum.

Best,
David
